=== lair101/dockerJenkins/dockerImage/master/files/iib-10.0.0.5/tools/plugins/com.ibm.j2ca.wmb.migration.core_8.0.0.201110071709/schema/j2caMigration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.ibm.com/xmlns/prod/websphere/j2ca/migration" targetNamespace="http://www.ibm.com/xmlns/prod/websphere/j2ca/migration">

<xsd:simpleType name="UpdateType">
  <xsd:restriction base="xsd:string">
    <xsd:enumeration value="update"/>
    <xsd:enumeration value="migration"/>
    <xsd:enumeration value="both"/>
  </xsd:restriction>
</xsd:simpleType> 

<xsd:complexType name="LibraryInfo">
  <xsd:attribute name="name" type="xsd:string"/>
  <xsd:attribute name="location" type="xsd:string" default=""/>
  <xsd:attribute name="native" type="xsd:boolean" default="false"/>
  <xsd:attribute name="import" type="xsd:boolean" default="false"/>
  <xsd:attribute name="delete" type="xsd:boolean" default="false" use="optional"/>
  <xsd:attribute name="validate" type="xsd:boolean" default="false"/>
  <xsd:attribute name="size" type="xsd:unsignedInt" use="optional"/>
  <xsd:attribute name="timestamp" type="xsd:dateTime" use="optional"/>
  <xsd:attribute name="validate_class" type="xsd:string" use="optional"/>
</xsd:complexType>

<xsd:complexType name="Parameter">
  <xsd:attribute name="name" type="xsd:string"/>
  <xsd:attribute name="value" type="xsd:string" default=""/>
  <xsd:attribute name="description" type="xsd:string" default="" use="optional"/>
</xsd:complexType>

<xsd:complexType name="AdapterInfo">
  <xsd:sequence>
    <xsd:element name="dependencies" minOccurs="0">
    <xsd:complexType>
    <xsd:sequence>
    	<xsd:element name="library" type="tns:LibraryInfo" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>	
    </xsd:complexType>
    </xsd:element>
  	<xsd:element name="update" type="tns:UpdateInfo" minOccurs="1" maxOccurs="unbounded"/>
  </xsd:sequence>
  <xsd:attribute name="name" type="xsd:string"/>
  <xsd:attribute name="version" type="xsd:string"/>
</xsd:complexType>



<xsd:complexType name="UpdateInfo">
<xsd:sequence>
    <xsd:element name="dependencies" minOccurs="0" maxOccurs="1">
    <xsd:complexType>
    <xsd:sequence>
    	<xsd:element name="library" type="xsd:string"  minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>	
    </xsd:complexType>
    </xsd:element>	
    <xsd:element name="tasks">
    <xsd:complexType>
    <xsd:sequence>
    	<xsd:element name="task" type="tns:TaskInfo" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>	
    </xsd:complexType>
    </xsd:element>		
    </xsd:sequence>
  <xsd:attribute name="version" type="xsd:string" use="required"/>
  <xsd:attribute name="type" type="tns:UpdateType" use="required"/>
</xsd:complexType>

<xsd:complexType name="UpdateFunctionType">
  <xsd:sequence>
       	<xsd:element name="parameter" type="tns:Parameter" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>  
    <xsd:attribute name="name" type="xsd:string"/>
</xsd:complexType>

<xsd:complexType name="TaskInfo">
  <xsd:sequence>
  	<xsd:element name="function" type="tns:UpdateFunctionType" minOccurs="0"/>
    <xsd:element name="subtasks" minOccurs="0" maxOccurs="1">
    <xsd:complexType>
    <xsd:sequence>
       	<xsd:element name="task" type="tns:TaskInfo" maxOccurs="unbounded"/>
    </xsd:sequence>   	
    </xsd:complexType>
    </xsd:element>	
  </xsd:sequence>
  <xsd:attribute name="name" type="xsd:string" use="required"/>
  <xsd:attribute name="description" type="xsd:string"/>
  <xsd:attribute name="update_type" type="tns:UpdateType" use="optional"/>
</xsd:complexType>

<xsd:element name="adapter" type="tns:AdapterInfo"/>

</xsd:schema>

=== lair101/dockerJenkins/dockerImage/master/files/iib-10.0.0.5/tools/plugins/com.ibm.j2ca.wmb.migration.sap_8.0.0.201110071709/updates_to_v610.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
 Licensed Materials - Property of IBM
 5724-L79
 Â© Copyright IBM Corporation 2007.  All Rights Reserved.
 US Government Users Restricted Rights - Use, duplication or disclosure
 restricted by GSA ADP Schedule Contract with IBM Corp. 
-->

<tns:adapter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://www.ibm.com/xmlns/prod/websphere/j2ca/migration" xsi:schemaLocation="http://www.ibm.com/xmlns/prod/websphere/j2ca/migration j2caMigration.xsd" name="(IBM WebSphere Adapter for SAP Software)|(IBM WebSphere Adapter for SAP Software with transaction support)" version="6\.1\.0.*">
	<update type="migration" version="(6\.0\.*.*)|(UNDEFINED)">
		<tasks>
			<task description="%JCA.SAPConnectorMigrationTask.Description" name="%JCA.SAPConnectorMigrationTask.Name">
				<function name="com.ibm.j2ca.wmb.migration.sap.v602_to_v610.SAPConnectorMigrationTask"/>
			</task>
			<task description="%JCA.SAPModuleMigrationTask.Description" name="%JCA.SAPModuleMigrationTask.Name">
				<function name="com.ibm.j2ca.wmb.migration.sap.v602_to_v610.SAPModuleMigrationTask"/>
			</task>
			<task description="%JCA.SAPAdapterNameValidationTask.Description" name="%JCA.SAPAdapterNameValidationTask.Name">
				<function name="com.ibm.j2ca.wmb.migration.sap.v602_to_v610.SAPAdapterNameValidationTask"/>
			</task>
			<task description="%JCA.SAPFunctionSelectorValidationTask.Description" name="%JCA.SAPFunctionSelectorValidationTask.Name">
				<function name="com.ibm.j2ca.wmb.migration.sap.v602_to_v610.SAPFunctionSelectorValidationTask"/>
			</task>
		</tasks>
	</update>
	
	<update type="migration" version="WBI">
		<tasks>
			<task description="%WBIA.SAPModuleMigrationTask.Description" name="%WBIA.SAPModuleMigrationTask.Name">
				<function name="com.ibm.j2ca.wmb.migration.sap.wbi_to_v620.SAPModuleMigrationTask"/>
			</task>
		</tasks>
	</update>
	
</tns:adapter>
